### ISSUE TITLE
Relocate method

### ISSUE THREAD

**Issue by maartenvangelder** [grrr-amsterdam/wordpress-scaffold#2]
WordPress supports an automatic relocation method intended to be a quick assist to getting a site working when relocating a site from one server to another.

Volgens mij moet deze constante in de application.php worden toegevoegd.

```
/* Change domain after deploy
@see: https://codex.wordpress.org/Changing_The_Site_URL#Relocate_method
*/
define('RELOCATE',true);
```

**Comment by schoenkaft** [comment]
As far as I can tell this will update the `WP_HOME` and the `WP_SITEURL` when login in, right?
However, these two variables should always come from the `.env`. When defining the `RELOCATE` it doesn't appear to update those variables in the database as well, since those aren't used anyway.

Or is this something that's more specific to a multisite setup?
